# web scraping using BeautifulSoup

Scrap data from this link: https://en.wikipedia.org/wiki/List_of_African_countries_by_area
        
focus on the first table:
- take rank , country and area.
- using pandas split are into two columns: km**2 and square mi

In [1]:
#import neccessary libraries
import requests
from bs4 import BeautifulSoup
import pandas as pd
import lxml.html as lh

In [2]:
#assingling link to the variable
link = 'https://en.wikipedia.org/wiki/List_of_African_countries_by_area'
page = requests.get(link)
print(page)

<Response [200]>

In [3]:
#Store the contents of the website under doc
doc = lh.fromstring(page.content)

In [4]:
#Parse data that are stored between <tr>..</tr> of HTML
tr_elements = doc.xpath('//tr')

In [5]:
#Check the length of the first 12 rows
[len(T) for T in tr_elements[:12]]

[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]

In [6]:
#Create empty list
col=[]
i=0
#For each row, store each first element (header) and an empty list
for t in tr_elements[0]:
    i+=1
    name=t.text_content()
    print ('%d:"%s"'%(i,name))
    col.append((name,[]))

1:"Rank
"
2:"Country[1][2][3]
"
3:"Area[a][b][4]
"
4:"Notes
"

In [7]:
# Since our first row is the header, data is stored on the second row onwards
for j in range(1,len(tr_elements)):
    #T is our j'th row
    T=tr_elements[j]
    
    #If row is not of size 4, the //tr data is not from our table 
    if len(T)!=4:
        break
    
    #i is the index of our column
    i=0
    
    #Iterate through each element of the row
    for t in T.iterchildren():
        data=t.text_content() 
        #Check if row is empty
        if i>0:
        #Convert any numerical value to integers
            try:
                data=int(data)
            except:
                pass
        #Append the data to the empty list of the i'th column
        col[i][1].append(data[:-1])
        #Increment i for the next column
        i+=1

In [8]:
[len(C) for (title,C) in col]

[54, 54, 54, 54]

In [9]:
Dict={title:column for (title,column) in col}
df=pd.DataFrame(Dict)

In [10]:
# new data frame with split value columns 
new = df["Area[a][b][4]\n"].str.split("(", n = 1, expand = True) 
  
# making separate first name column from new data frame 
df["Areakm**2"]= new[0] 
  
# making separate last name column from new data frame 
df["Areasquare mi"]= new[1] 
  
# Dropping old Name columns 
df.drop(columns =["Area[a][b][4]\n"], inplace = True)

In [11]:
df

,Rank,Country[1][2][3],Notes,Areakm**2,Areasquare mi
0,1,Algeria,,"2,381,741 km2","919,595 sq mi)"
1,2,Democratic Republic of the Congo,,"2,344,858 km2","905,355 sq mi)"
2,3,Sudan,,"1,861,484 km2","718,723 sq mi)"
3,4,Libya,,"1,759,540 km2","679,362 sq mi)"
4,5,Chad,,"1,284,000 km2","495,755 sq mi)"
5,6,Niger,,"1,267,000 km2","489,191 sq mi)"
6,7,Angola,,"1,246,700 km2","481,354 sq mi)"
7,8,Mali,,"1,240,192 km2","478,841 sq mi)"
8,9,South Africa,,"1,221,037 km2","471,445 sq mi)"
9,10,Ethiopia,,"1,104,300 km2","426,373 sq mi)"
10,11,Mauritania,,"1,030,700 km2","397,955 sq mi)"
11,12,Egypt[a],"1,010,408 km2 (390,121 sq mi) when including S...","1,001,449 km2","386,662 sq mi)"
12,13,Tanzania,,"945,203 km2","364,945 sq mi)"
13,14,Nigeria,,"923,768 km2","356,669 sq mi)"
14,15,Namibia,,"825,418 km2","318,696 sq mi)"
15,16,Mozambique,,"801,590 km2","309,496 sq mi)"
16,17,Zambia,,"752,614 km2","290,586 sq mi)"
17,18,Morocco,"446,550 km2 (172,414 sq mi) excluding all disp...","710,850 km2","274,461 sq mi)"
18,19,South Sudan,,"644,329 km2","248,777 sq mi)"
19,20,Somalia,,"637,657 km2","246,201 sq mi)"
20,21,Central African Republic,,"622,984 km2","240,535 sq mi)"
21,22,Madagascar,,"587,041 km2","226,658 sq mi)"
22,23,Botswana,,"581,726 km2","224,606 sq mi)"
23,24,Kenya,,"580,367 km2","224,081 sq mi)"
24,25,Cameroon,,"475,442 km2","183,569 sq mi)"
25,26,Zimbabwe,,"390,757 km2","150,872 sq mi)"
26,27,Republic of the Congo,,"342,000 km2","132,047 sq mi)"
27,28,Ivory Coast (Côte d'Ivoire),,"322,460 km2","124,503 sq mi)"
28,29,Burkina Faso,,"274,000 km2","105,792 sq mi)"
29,30,Gabon,,"267,668 km2","103,347 sq mi)"
30,31,Guinea,,"245,857 km2","94,926 sq mi)"
31,32,Ghana,,"238,534 km2","92,098 sq mi)"
32,33,Uganda,,"236,040 km2","91,136 sq mi)"
33,34,Senegal,,"196,723 km2","75,955 sq mi)"
34,35,Tunisia,,"163,610 km2","63,170 sq mi)"
35,36,Malawi,,"118,484 km2","45,747 sq mi)"
36,37,Eritrea,,"117,600 km2","45,406 sq mi)"
37,38,Benin,,"112,622 km2","43,484 sq mi)"
38,39,Liberia,,"111,369 km2","43,000 sq mi)"
39,40,Sierra Leone,,"71,740 km2","27,699 sq mi)"
40,41,Togo,,"56,785 km2","21,925 sq mi)"
41,42,Guinea-Bissau,,"36,125 km2","13,948 sq mi)"
42,43,Lesotho,,"30,355 km2","11,720 sq mi)"
43,44,Equatorial Guinea,,"28,051 km2","10,831 sq mi)"
44,45,Burundi,,"27,830 km2","10,745 sq mi)"
45,46,Rwanda,,"26,798 km2","10,347 sq mi)"
46,47,Djibouti,,"23,200 km2","8,958 sq mi)"
47,48,Eswatini (Swaziland),,"17,364 km2","6,704 sq mi)"
48,49,"Gambia, The",,"10,380 km2","4,008 sq mi)"
49,50,Cape Verde,,"4,033 km2","1,557 sq mi)"
50,51,Comoros,"1,659 km2 excluding the disputed island of May...","2,235 km2",863 sq mi)
51,52,Mauritius,,"2,040 km2",788 sq mi)
52,53,São Tomé and Príncipe,,964 km2,372 sq mi)
53,54,Seychelles,,451 km2,174 sq mi)